### ISSUE TITLE
blyat

### ISSUE THREAD

**Issue by Not-Hax** [SexyTeam/Deneb#5]
```
Caused by: java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject
at club.deneb.client.client.ConfigManager.loadClient(ConfigManager.kt:228)
at club.deneb.client.client.ConfigManager.loadAll(ConfigManager.kt:391)
```
and i deleted old configs

**Comment by SpartanB312** [comment]
Fixed ,see 0.5.3
